"""chess

Revision ID: 97016affce2f
Revises: b0d7819632ce
Create Date: 2026-02-24 15:51:36.880552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97016affce2f'
down_revision: Union[str, Sequence[str], None] = 'b0d7819632ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_group', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('chats_pkey'))
    )
    op.create_index(op.f('chats_id_idx'), 'chats', ['id'], unique=False)
    op.create_table('chat_members',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('chat_members_chat_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('chat_members_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_members_pkey'))
    )
    op.create_index(op.f('chat_members_id_idx'), 'chat_members', ['id'], unique=False)
    op.add_column('messages', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.add_column('messages', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('messages_sender_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_recipient_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_user_id_fkey'), 'messages', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('messages_chat_id_fkey'), 'messages', 'chats', ['chat_id'], ['id'])
    op.drop_column('messages', 'sender_id')
    op.drop_column('messages', 'recipient_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('messages_chat_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_user_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_recipient_id_fkey'), 'messages', 'users', ['recipient_id'], ['id'])
    op.create_foreign_key(op.f('messages_sender_id_fkey'), 'messages', 'users', ['sender_id'], ['id'])
    op.drop_column('messages', 'user_id')
    op.drop_column('messages', 'chat_id')
    op.drop_index(op.f('chat_members_id_idx'), table_name='chat_members')
    op.drop_table('chat_members')
    op.drop_index(op.f('chats_id_idx'), table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
